on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: before script
        run: cd examples

      - name: Install dependencies
        run: npm install

      - name: Run app
        run: npm run dev &

      - name: Run Cypress
        run: npm run cy:run

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.8.0
